const todoList = [
  "Buy groceries",
  "Pay bills",
  "Clean the house",
  "Exercise",
  "Finish the report",
  "Call mom",
  "Read a book",
  "Walk the dog",
  "Go for a run",
  "Water the plants",
  "Cook dinner",
  "Do the laundry",
  "Study for exam",
  "Write a blog post",
  "Practice coding",
  "Schedule appointment",
  "Volunteer at a shelter",
  "Organize desk",
  "Call a friend",
  "Plan a trip",
  "Watch a movie",
  "Take a nap",
  "Learn a new skill",
  "Attend a workshop",
  "Buy a birthday gift",
  "Send a thank-you note",
  "Clean out the fridge",
  "Start a journal",
  "Meditate for 10 minutes",
  "Fix a broken item",
  "Try a new recipe",
  "Go stargazing",
  "Sort out old clothes",
  "Create a budget",
  "Donate to charity",
  "Read the news",
  "Take a nature walk",
  "Learn to play an instrument",
  "Visit a museum",
  "Write a poem",
  "Do a random act of kindness",
  "Explore a new neighborhood",
  "Call a family member",
  "Plan a picnic",
  "Build a DIY project",
  "Join a book club",
  "Learn a magic trick",
  "Write a letter to yourself",
  "Research a new hobby",
  "Paint a picture",
  "Start a compost bin",
  "Try a new restaurant",
  "Do a puzzle",
  "Listen to a podcast",
  "Plant flowers in the garden",
  "Play a board game",
  "Take a cooking class",
  "Practice mindfulness",
  "Create a vision board",
  "Learn a new language",
  "Go to a farmer's market",
  "Declutter a room",
  "Visit a local landmark",
  "Do a home workout",
  "Attend a live performance",
  "Explore a nearby park",
  "Try a new hairstyle",
  "Play with a pet",
  "Write a short story",
  "Try a new type of cuisine",
  "Do a science experiment",
  "Watch a documentary",
  "Take a photography walk",
  "Do a crossword puzzle",
  "Learn to dance",
  "Write a to-do list for tomorrow",
  "Make a handmade gift",
  "Watch the sunrise",
  "Write down your dreams",
  "Have a technology-free day",
  "Take a bike ride",
  "Create a playlist of favorite songs",
  "Learn about a historical event",
  "Play a video game",
  "Try a new type of exercise",
  "Do a DIY home improvement",
  "Visit a local library",
  "Write a gratitude journal",
  "Join a community event",
  "Make a list of places to visit",
  "Try a new type of tea",
  "Do a brain-teaser puzzle",
  "Watch the sunset",
  "Create a scrapbook",
  "Go on a road trip",
  "Learn to juggle",
  "Explore a nearby forest",
  "Try a new board game",
  "Take a dance class",
  "Visit an art gallery",
  "Write a list of things you love about yourself",
  "Attend a meditation session",
  "Have a picnic in the park",
  "Try a new type of art",
  "Do a virtual escape room",
  "Learn to do origami",
  "Watch a stand-up comedy show",
  "Have a spa day at home",
  "Learn to solve a Rubik's cube",
  "Do a DIY fashion project",
  "Visit a botanical garden",
  "Write a letter to your future self",
  "Make a list of favorite quotes",
  "Try a new type of dessert",
  "Do a word search puzzle",
  "Explore a local market",
  "Try a new type of meditation",
  "Watch a classic movie",
  "Take a pottery class",
  "Learn to do magic tricks",
  "Visit a wildlife sanctuary",
  "Write a list of personal goals",
  "Have a movie marathon",
  "Try a new outdoor activity",
  "Do a DIY art project",
  "Explore a nearby lake",
  "Take a singing lesson",
  "Visit a historical site",
  "Write a short gratitude letter to someone",
  "Try a new type of cuisine",
  "Do a nature scavenger hunt",
  "Watch a wildlife documentary",
  "Have a game night with friends",
  "Learn to play chess",
  "Visit a science museum",
  "Write a letter to a future grandchild",
  "Make a list of places you want to travel to",
  "Try a new form of exercise",
  "Do a DIY woodworking project",
  "Explore a nearby beach",
  "Take a cooking class",
  "Learn to do calligraphy",
  "Visit a planetarium",
  "Write a letter to your past self",
  "Try a new type of craft",
  "Do a virtual museum tour",
  "Watch a documentary on space exploration",
  "Have a karaoke night",
  "Learn to do card tricks",
  "Visit a local zoo",
  "Write a list of things you're grateful for",
  "Try a new type of music",
  "Do a virtual art class",
  "Explore a nearby mountain",
  "Take a photography class",
  "Visit a local farm",
  "Write a letter to a mentor or role model",
  "Try a new form of dance",
  "Do a DIY gardening project",
  "Watch a historical documentary",
  "Have a board game marathon",
  "Learn to play a musical instrument",
  "Visit a natural hot spring",
  "Write a letter to your favorite author",
  "Try a new type of exercise",
  "Do a virtual cooking class",
  "Explore a nearby city",
  "Take a painting class",
  "Learn to do pottery",
  "Visit a local art fair",
  "Write a list of inspiring people",
  "Try a new form of meditation",
  "Do a DIY home decor project",
  "Watch a wildlife livestream",
  "Have a themed costume party",
  "Learn to do balloon animals",
  "Visit a local theater performance",
  "Write a letter to your future self",
  "Try a new type of cuisine",
  "Do a virtual yoga class",
  "Explore a nearby nature reserve",
  "Take a woodworking class",
  "Visit a historical reenactment",
  "Write a letter to your future child",
  "Try a new type of craft",
  "Do a virtual fitness class",
  "Watch a documentary on marine life",
  "Have a movie night under the stars",
  "Learn to do flower arrangements",
  "Visit a botanical garden",
  "Write a list of your favorite books",
  "Try a new form of art",
  "Do a virtual escape room",
  "Explore a nearby hiking trail",
  "Take a dancing class",
  "Visit an art gallery",
  "Write a list of personal affirmations",
];

export function generateRandomTodo() {
  return todoList[randInt(todoList.length)];
}

function randInt(lessThan: number) {
  return Math.floor(Math.random() * lessThan);
}

export function hexToBytes(hex: string) {
  const ret = new Uint8Array(hex.length / 2);
  for (let c = 0; c < hex.length; c += 2) {
    ret[c / 2] = parseInt(hex.substring(c, c + 2), 16);
  }
  return ret;
}

export function bytesToHex(bytes: Uint8Array) {
  let hex: string[] = [];
  for (let i = 0; i < bytes.length; i++) {
    let current = bytes[i] < 0 ? bytes[i] + 256 : bytes[i];
    hex.push((current >>> 4).toString(16));
    hex.push((current & 0xf).toString(16));
  }
  return hex.join("");
}
